name: OWASP ZAP Integration with GitHub Actions

on: [push]

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    name: Scan the web application
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.7.0
        continue-on-error: true
        with:
          docker_name: 'owasp/zap2docker-stable'
          target: 'https://6496-2401-4900-5046-f735-9496-27fe-bad-d11a.in.ngrok.io/login.html'
          rules_file_name: '.zap/rules.tsv'
          cmd_options: '-a'